"""Fold the reads-tier verdicts (float_reads_{year}.json — the saved output
of the blind-read/adjudication workflow) into float_overrides.py.

Mapping:
* two blind reads reproduced the extraction      -> CONFIRMED (2BLIND)
* sonnet ruled the extraction right              -> CONFIRMED (SONNET)
* sonnet ruled the cover discloses no float      -> NO_FLOAT
* sonnet ruled different rows                    -> OVERRIDES (pending the
  adversarial verification pass, which stamps each entry)

The generated tables are printed to float_overrides_generated.py for review
and adversarial verification — they are merged into float_overrides.py only
after that pass, never blindly.
"""

# ---- EDIT THIS --------------------------------------------------------------
year = 2025
# -----------------------------------------------------------------------------

import json
import os

import pandas as pd

try:
    from config import DATA_DIR
except ImportError:
    raise RuntimeError(
        "config.py not found. Copy config.example.py to config.py and set "
        "USER_AGENT and DATA_DIR."
    )

directory = DATA_DIR.replace("\\", "/")
with open(os.path.join(directory, "float_reads_%d.json" % year),
          encoding="utf-8") as f:
    reads = json.load(f)

ext = pd.read_csv(os.path.join(directory, "float_extraction_%d.csv" % year),
                  dtype=str, keep_default_na=False)
ext_by = {a: [(float(r["value"]), r["as_of"]) for _, r in g.iterrows()]
          for a, g in ext.groupby("accession")}


def rows_match_extraction(acc, ruled_rows):
    """True when the ruled rows equal the CURRENT extraction (the extractor
    may have been generalized since the ruling was made)."""
    cur = sorted(ext_by.get(acc, []))
    rr = sorted((float(x["value_usd"]), x.get("as_of", ""))
                for x in ruled_rows)
    if len(cur) != len(rr):
        return False
    for (cv, cd), (rv, rd) in zip(cur, rr):
        if abs(cv - rv) > max(1.0, cv * 0.005):
            return False
        if cd and rd and cd != rd:
            return False
    return True


def fmt_value(v):
    return ("%d" % v) if float(v) == int(v) else ("%.2f" % v)


confirmed, no_float, overrides, neg_findings = {}, {}, {}, []

for entry in reads["confirmed"]:
    tier, status, acc = entry.split("|")
    if tier == "unresolved":
        confirmed[acc] = "READS_2BLIND_CONFIRMED"

for r in reads["rulings"]:
    acc, status, tier = r["a"], r["s"], r["t"]
    rul = r["ruling"]
    kind = rul.get("no_float_kind") or "ABSENT"
    prov = "sonnet adjudication: %s" % rul["rationale"].strip()
    if tier == "negative":
        if rul["ruling"] == "NO_FLOAT" or not rul["rows"]:
            continue  # negative class confirmed by adjudication too
        neg_findings.append((acc, status, rul))
        continue
    if rul["ruling"] == "EXTRACTOR_RIGHT" or \
            (rul["rows"] and rows_match_extraction(acc, rul["rows"])):
        confirmed[acc] = "READS_SONNET_CONFIRMED"
    elif rul["ruling"] == "NO_FLOAT" or not rul["rows"]:
        no_float[acc] = "%s; %s" % (kind, prov)
    else:
        overrides[acc] = {
            "rows": [{"cover": fmt_value(x["value_usd"]),
                      "xbrl": "", "as_of": x.get("as_of", ""),
                      "label": x.get("label", ""), "flags": ""}
                     for x in rul["rows"]],
            "provenance": "%s [%s -> %s]" % (prov, status, rul["ruling"]),
        }

# negative-class filings where adjudication found a float the pipeline
# missed: they become overrides too (the serious finding) — unless the
# extractor has since been generalized and now reproduces the ruling
for acc, status, rul in neg_findings:
    if rul["rows"] and rows_match_extraction(acc, rul["rows"]):
        confirmed[acc] = "READS_SONNET_CONFIRMED"
        continue
    overrides[acc] = {
        "rows": [{"cover": fmt_value(x["value_usd"]),
                  "xbrl": "", "as_of": x.get("as_of", ""),
                  "label": x.get("label", ""), "flags": ""}
                 for x in rul["rows"]],
        "provenance": "negative-class sample (%s) overturned by sonnet: %s"
                      % (status, rul["rationale"].strip()),
    }

out = os.path.join(directory, "float_overrides_generated.py")
with open(out, "w", encoding="utf-8") as f:
    f.write("# generated by 13_fold_float_reads.py — review + adversarial\n"
            "# verification before merging into float_overrides.py\n\n")
    f.write("CONFIRMED = {\n")
    for k in sorted(confirmed):
        f.write('    "%s": "%s",\n' % (k, confirmed[k]))
    f.write("}\n\nNO_FLOAT = {\n")
    for k in sorted(no_float):
        f.write('    "%s": %r,\n' % (k, no_float[k]))
    f.write("}\n\nOVERRIDES = {\n")
    for k in sorted(overrides):
        f.write('    "%s": %r,\n' % (k, overrides[k]))
    f.write("}\n")

print("wrote %s" % out)
print("confirmed: %d, no_float: %d, overrides: %d, negative findings: %d"
      % (len(confirmed), len(no_float), len(overrides), len(neg_findings)))
