"""The committed record of every filing whose final rows do NOT come from
the extractor alone — the deterministic tail of the validation ladder.

Three tables, all keyed by accession number:

* CONFIRMED — extractor rows accepted on non-XBRL evidence: two blind
  independent reads (and/or a sonnet adjudication) agreed with the
  extraction. The dataset keeps the extractor's rows; only the validation
  provenance differs from XBRL-matched filings.
* NO_SHARES — filings whose cover discloses no share count (debt-only
  subsidiaries, securitization vehicles, fund trusts). Value: a short
  category string. These appear in the coverage table, never as rows.
* OVERRIDES — filings where the verified cover reading differs from the
  extraction; the rows below replace the extractor's output entirely.
  Each entry carries its provenance.

Every entry was produced by the tier-2/3 process logged in progress.md:
two blind haiku reads, sonnet adjudication of every conflict, and (where
noted) an Opus-tier final check. Regenerating the dataset on any machine
uses this file verbatim — no sub-agent is ever consulted at build time.

This file is GENERATED by the tier-3 reconciliation and then committed;
edit only with a verified ruling in hand.
"""

PROVENANCE = "2 blind haiku reads + sonnet adjudication, 2026-06-11"

CONFIRMED = {
    # accession: validation tag
}

NO_SHARES = {
    # accession: category
}

OVERRIDES = {
    # accession: {"rows": [{"value", "label", "share_type",
    #                       "class_designator", "as_of", "registrant"}],
    #             "why": "...", "provenance": "..."}
}
